#pragma once

// Phase-5 spike (in-game QR display, see docs/phone-companion-design.md):
// registers the "duskqr:" RmlUi texture-provider scheme so an
// <img src="duskqr://pairing"/> in Settings shows the live phone-pairing
// QR, generated by phone_spike_pairing.cpp. Same mechanism as
// remote_texture_provider.hpp/.cpp (register_remote_texture_provider),
// just synchronous — the QR bitmap is already in memory, no fetch/cache
// state machine needed. Gated by DUSK_PHONE_SPIKE; no-op stubs otherwise,
// so callers in ui.cpp need no #if of their own.

namespace dusk::ui {

void register_qr_texture_provider() noexcept;
void unregister_qr_texture_provider() noexcept;

}  // namespace dusk::ui
